from fastapi_mail import ConnectionConfig, FastMail, MessageSchema, MessageType

from app.core.settings import settings
from pathlib import Path

conf = ConnectionConfig(
    MAIL_USERNAME=settings.mail_username,
    MAIL_PASSWORD=settings.mail_password,
    MAIL_FROM=settings.mail_from,
    MAIL_FROM_NAME=settings.mail_from_name,
    MAIL_SERVER=settings.mail_server,
    MAIL_PORT=settings.mail_port,
    MAIL_STARTTLS=settings.mail_starttls,
    MAIL_SSL_TLS=settings.mail_ssl_tls,
    VALIDATE_CERTS=settings.mail_validate_certs,
)

class MailService:
    """
    Service responsible for sending application emails.

    This centralizes all email-related operations such as:
    - Password reset
    - Email verification
    - Two-factor authentication (2FA)
    - Welcome emails
    - Notifications
    """

    def __init__(self) -> None:
        self.fast_mail = FastMail(conf)

    async def send_password_reset_email(
        self,
        email: str,
        reset_url: str,
    ) -> None:
        """
        Send a password reset email containing the reset link.

        Args:
            email: Recipient's email address.
            reset_url: Password reset URL generated by the authentication service.
            
        """
        template_path = (
        Path(__file__).parent
        / "templates"
        / "reset_password.html"
    )

        html_body = (
            template_path.read_text(encoding="utf-8")
            .replace("{{ reset_link }}", reset_url)
        )
        
        
        message = MessageSchema(
            subject="Reset Your STMS Password",
            recipients=[email],
            body=html_body,
            subtype=MessageType.html,
        )
        await self.fast_mail.send_message(message)