"""add reset password fields to accounts

Revision ID: 166cd3416bec
Revises: a0e17baa64c5
Create Date: 2026-07-20 11:46:53.837848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166cd3416bec'
down_revision: Union[str, Sequence[str], None] = 'a0e17baa64c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('reset_password_token_hash', sa.String(length=64), nullable=True))
    op.add_column('accounts', sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'reset_password_token_expires_at')
    op.drop_column('accounts', 'reset_password_token_hash')
    # ### end Alembic commands ###
