"""Initial STMS schema

Revision ID: a0e17baa64c5
Revises: 
Create Date: 2026-07-15 12:40:17.369212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e17baa64c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('company_short_name', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('customer_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('company_short_name'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.Enum('PLATFORM_OWNER', 'SUPER_ADMIN', 'CUSTOMER_ADMIN', 'VENDOR', name='accounttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'SUSPENDED', name='accountstatus'), nullable=False),
    sa.Column('mobile_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_code'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.drop_table('customers')
    # ### end Alembic commands ###
