"""add customer_uid to customers

Revision ID: d920dc06ddca
Revises: bc6b543309ba
Create Date: 2026-07-15 10:50:19.095465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd920dc06ddca'
down_revision: Union[str, Sequence[str], None] = 'bc6b543309ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_uid', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'customers', ['customer_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'customer_uid')
    # ### end Alembic commands ###
