"""create accounts table

Revision ID: eb451d262e15
Revises: 1ccdac27d513
Create Date: 2026-07-23 17:03:43.245785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb451d262e15'
down_revision: Union[str, Sequence[str], None] = '1ccdac27d513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('accounts', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('accounts', sa.Column('parent_account_id', sa.BigInteger(), nullable=True))
    op.add_column('accounts', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.add_column('accounts', sa.Column('language', sa.String(length=20), nullable=False))
    op.add_column('accounts', sa.Column('date_format', sa.String(length=20), nullable=False))
    op.add_column('accounts', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('is_rtl', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('accounts', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(

        "fk_accounts_created_by",

        "accounts",

        "accounts",

        ["created_by"],

        ["account_id"],

    )

    op.create_foreign_key(

        "fk_accounts_parent_account",

        "accounts",

        "accounts",

        ["parent_account_id"],

        ["account_id"],

    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_accounts_parent_account",
        "accounts",
        type_="foreignkey",
    )

    op.drop_constraint(
        "fk_accounts_created_by",
        "accounts",
        type_="foreignkey",
    )
    op.drop_column('accounts', 'last_login_at')
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    op.drop_column('accounts', 'created_by')
    op.drop_column('accounts', 'is_rtl')
    op.drop_column('accounts', 'two_factor_enabled')
    op.drop_column('accounts', 'date_format')
    op.drop_column('accounts', 'language')
    op.drop_column('accounts', 'timezone')
    op.drop_column('accounts', 'parent_account_id')
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###
