"""make account email unique and not null

Revision ID: f312f9051c0b
Revises: 5b1fc8586183
Create Date: 2026-07-24 11:21:49.160658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f312f9051c0b'
down_revision: Union[str, Sequence[str], None] = '5b1fc8586183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(
        'uq_accounts_email',
        'accounts',
        ['email'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_accounts_email',
        'accounts',
        type_='unique',
    )
    op.alter_column('accounts', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
